version: "3.8"
services:
  # To connect: in the poackage.json PROJECT must be
  #"start": "ng serve --host=0.0.0.0 --port 4200",
  node:
    image: node:10
    container_name: node_${PROJECT_NAME}
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    #Node with command:
    #command: tail -F anything
    #First Install:
    #command: sh -c "npm install && npm install -g migrate-mongo && npm run dev"
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017
    ports:
      - ${NODE_PORT}:4200
    volumes:
      - ${PROJECT_PATH}:/app
    networks:
      - app-network

  graphql:
    image: node:10
    container_name: graphql_${PROJECT_NAME}
    working_dir: /app
    #command: tail -F anything
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    ports:
      - ${GRAPHQL_PORT}:${GRAPHQL_PORT}
    volumes:
      - ${GRAPHQL_PATH}:/app
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    container_name: mongo_${PROJECT_NAME}
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=touch_it
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${DATA_PATH}:/data/db
    networks:
      - app-network

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient_${PROJECT_NAME}
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin&ssl=false
    depends_on:
      - mongo
    ports:
      - ${MONGOCLIENT_PORT}:3000
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
